name: "Deploy Preview"

on:
  push:
    branches-ignore:
      - main
  pull_request_target:
    # enable runs for this workflow when labeled as safe only
    # prevent execution when the workflow itself is modified from a fork
    types:
      - labeled
      - synchronize

jobs:
  deploy-preview:
    name: Build & Deploy
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'safe'))
      || (github.event_name == 'push' && github.event.push.repository.full_name == github.repository)
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Build Assets
        run: npm ci && npm run prod

      - name: Fetch Documentation
        run: |
          python -m pip install poetry
          poetry install --no-dev
          poetry run python bin/website build

      - name: Start Deployment
        uses: bobheadxi/deployments@v0.5.2
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: Preview

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.83.1"

      - name: Build
        run: hugo -v

      - name: Deploy
        uses: amondnet/vercel-action@v20
        id: vercel-action
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          scope: python-poetry
          github-comment: false
          working-directory: public

      - name: Update Deployment Status
        uses: bobheadxi/deployments@v0.5.2
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: ${{ steps.vercel-action.outputs.preview-url }}
